### ISSUE TITLE
Catalog Next Package - Project and File name lists for Scripture resources

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/tc-create-app#878]
This issues covers two more of the local catalog API, namely, to return a list of projects and to return a list of filenames. Note that for non-scripture resources:
- the list of projects is not useful. For example, Translation Academy articles are all associated with the single "translate" project.
- furthermore, each TA article is actually composed of three markdown files. So the "list" of filenames will need to be a navigable indented structure that is presented to the user.

With this in mind, this issue covers *only* scripture resources, namely: 'twl', 'tn', 'tq', 'obs', 'obs-tq', 'obs-tn', 'obs-sn', 'obs-sq', plus the Hebrew and Greek Original Languages.

- [ ] Implement the function to return a list of projects from the manifest
- [ ] Implement the function to return a list of filenames from the manifest
- [ ] Both lists must returned in the sort order specified in the manifest
- [ ] Each list must be cached once parsed from the manifest so that it is only done once per session
- [ ] Add demo for above
- [ ] Add unit tests for above

**Comment by mandolyte** [comment]
**Description of Requirements**

Two functions will be implements:
- getProjects(): return the list of projects from the manifest. This would be used to provide a list of projects from which the user may select.
- getFilenames(): return a list of the files that correspond to the project(s) in the sort order (if any) provided by the manifest. This would be used to provide a file list from which the user may select.

**Technical Requirements**

- lists must be sorted per manifest
- lists must be cached for subsequent use in same session

Here is an example from the en_twl manifest show the first couple of manifest project entries. These project entries are the source for the lists returned:

```yaml
projects:
  -
    title: 'Genesis'
    versification: 'ufw'
    identifier: 'gen'
    sort: 1
    path: './twl_GEN.tsv'
    categories: [ 'bible-ot' ]

  -
    title: 'Exodus'
    versification: 'ufw'
    identifier: 'exo'
    sort: 2
    path: './twl_EXO.tsv'
    categories: [ 'bible-ot' ]

  -
    title: 'Leviticus'
    versification: 'ufw'
    identifier: 'lev'
    sort: 3
    path: './twl_LEV.tsv'
    categories: [ 'bible-ot' ]
```
