### ISSUE TITLE
Catalog Next Package - Project and File name lists for Translation Academy

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/tc-create-app#879]
This issue covers the implementation of project and filename lists for TA. Of note:

- TA articles are under the folder `translate` (`unfoldingword/en_ta/translate`)
- There is a single project named 'translate' -- so a project list isn't helpful
- Each article is in its own folder that is named per the article title
- Each article is actually composed of three files (see details in next post).

Here are the deliverables:
- [ ] Implement TA specific functions for TA articles to provide file lists that correspond to the TA folder structure.
- [ ] The list must be sorted by article name (same as folder names) and the list will be an indented structure so that all three markdown files are selectable.
- [ ] A demo showing TA functionality
- [ ] A unit test for TA

**Comment by mandolyte** [comment]
**Description of Requirements**

There will be TA-specific implementations of the two functions `getProjects` and `getFilenames`.

Here is manifest entry for the projects in the manifest for TA. Note that only 'translate' contains content of interest. Hence the getProject function for TA might just return "translate" as a hardcoded string.
```yaml
projects:
  -
    categories:
      - 'ta'
    identifier: 'intro'
    path: './intro'
    sort: 0
    title: 'Introduction to unfoldingWord® Translation Academy'
    versification:
  -
    categories:
      - 'ta'
    identifier: 'process'
    path: './process'
    sort: 1
    title: 'Process Manual'
    versification:
  -
    categories:
      - 'ta'
    identifier: 'translate'
    path: './translate'
    sort: 2
    title: 'Translation Manual'
    versification:
  -
    categories:
      - 'ta'
    identifier: 'checking'
    path: './checking'
    sort: 3
    title: 'Checking Manual'
    versification:
```

The filenames on the other hand will be a folder structure, where the folders are named by the article and contain three files. Here is an example from `unfoldingword/en_ta/translate/bita-animals`, where `bita-animals` is the article name and is a folder. The folder contains three files:
```
01.md
title.md
sub-title.md
```
Where the main body of the article is in `01.md`.
