### ISSUE TITLE
Catalog Next Package - Project and File name lists for Translation Words

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/tc-create-app#880]
This issue covers the implementation of project and filename lists for TW. Of note:

- TW articles are under the folder `bible` (`unfoldingword/en_tw/bible`)
- There is a single project named 'bible' -- so a project list isn't helpful
- The folder 'bible' has three sub-folders which organize the TW articles into three categories: 'kt', 'names', and 'other'
- Each article is in a markdown file with the following format `title.md`; thus the article title is filename sans the '.md' extension

Here are deliverables:
- [ ] Implement TW specific functions for TW articles to provide file lists that correspond to the nested TW folder structure.
- [ ] The list must be sorted by category and article name and the list will be an indented structure
- [ ] A demo showing TW functionality
- [ ] A unit test for above

**Comment by mandolyte** [comment]
**Description of Requirements**

There will be TW-specific implementations of the two functions `getProjects` and `getFilenames`.

Here is manifest entry for the projects in the manifest for TW. Hence the getProject function for TW might just return "bible" as a hardcoded string.

```yaml
projects:
  -
    categories:
    identifier: 'bible'
    path: './bible'
    sort: 0
    title: 'unfoldingWord® Translation Words'
    versification:
```

As an example, the "kt" article for the "altar" article is at:
`unfoldingword/en_tw/bible/kt/altar.md`.
